//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1586.0.
// 
namespace GT.Provisioning.Core.ExtensibilityHandlers.XML
{
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class WebProviderConfiguration
    {

        private WebProviderConfigurationWeb[] websField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("web", IsNullable = false)]
        public WebProviderConfigurationWeb[] webs
        {
            get
            {
                return this.websField;
            }
            set
            {
                this.websField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WebProviderConfigurationWeb
    {

        private WebProviderConfigurationWebRoleAssignment[] roleAssignmentsField;

        private WebProviderConfigurationWebList[] listsField;

        private int languageField;

        private bool languageFieldSpecified;

        private string titleField;

        private string descriptionField;

        private string urlField;

        private bool useSamePermissionsAsParentSiteField;

        private bool useSamePermissionsAsParentSiteFieldSpecified;

        private bool inheritNavigationField;

        private bool inheritNavigationFieldSpecified;

        private string baseTemplateField;

        private string pnPTemplateField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("RoleAssignment", IsNullable = false)]
        public WebProviderConfigurationWebRoleAssignment[] RoleAssignments
        {
            get
            {
                return this.roleAssignmentsField;
            }
            set
            {
                this.roleAssignmentsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("List", IsNullable = false)]
        public WebProviderConfigurationWebList[] Lists
        {
            get
            {
                return this.listsField;
            }
            set
            {
                this.listsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int Language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LanguageSpecified
        {
            get
            {
                return this.languageFieldSpecified;
            }
            set
            {
                this.languageFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool UseSamePermissionsAsParentSite
        {
            get
            {
                return this.useSamePermissionsAsParentSiteField;
            }
            set
            {
                this.useSamePermissionsAsParentSiteField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool UseSamePermissionsAsParentSiteSpecified
        {
            get
            {
                return this.useSamePermissionsAsParentSiteFieldSpecified;
            }
            set
            {
                this.useSamePermissionsAsParentSiteFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool InheritNavigation
        {
            get
            {
                return this.inheritNavigationField;
            }
            set
            {
                this.inheritNavigationField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool InheritNavigationSpecified
        {
            get
            {
                return this.inheritNavigationFieldSpecified;
            }
            set
            {
                this.inheritNavigationFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string BaseTemplate
        {
            get
            {
                return this.baseTemplateField;
            }
            set
            {
                this.baseTemplateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PnPTemplate
        {
            get
            {
                return this.pnPTemplateField;
            }
            set
            {
                this.pnPTemplateField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WebProviderConfigurationWebRoleAssignment
    {

        private string principalField;

        private string roleDefinitionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Principal
        {
            get
            {
                return this.principalField;
            }
            set
            {
                this.principalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RoleDefinition
        {
            get
            {
                return this.roleDefinitionField;
            }
            set
            {
                this.roleDefinitionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WebProviderConfigurationWebList
    {

        private WebProviderConfigurationWebListFolder[] foldersField;

        private string nameField;

        private string urlField;

        private string templateTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Folder", IsNullable = false)]
        public WebProviderConfigurationWebListFolder[] Folders
        {
            get
            {
                return this.foldersField;
            }
            set
            {
                this.foldersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string templateType
        {
            get
            {
                return this.templateTypeField;
            }
            set
            {
                this.templateTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    public partial class WebProviderConfigurationWebListFolder
    {

        private string nameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
}
